### ISSUE TITLE
Count a non-existing collection

### ISSUE THREAD

**Issue by eibrahim** [craiggwilson/Simple.Data.MongoDB#10]
When I run this command:

db.Feeds.FindAll().Count()

I get this exception

Query returned no rows; cannot return scalar value.

The Feeds collection doesn't exist and hasn't been created yet...  Is that way I am getting?  

I haven't tried creating the collection manually then calling the command again.

**Comment by craiggwilson** [comment]
I just pushed a new version to nuget.  Post back if it doesn't fix your problem.
