### ISSUE TITLE
LoaderException

### ISSUE THREAD

**Issue by ghost** [craiggwilson/Simple.Data.MongoDB#12]
This has happened a few times: basically, I install the Nuget package via the VS package manager. Upon a clean/rebuild, I get the following exception:

`{"Method 'GetKey' in type 'Simple.Data.MongoDB.MongoAdapter' 
    from assembly 'Simple.Data.MongoDB, Version=0.12.0.1, Culture=neutral, PublicKeyToken=null' 
does not have an implementation.":"Simple.Data.MongoDB.MongoAdapter"}`

Any ideas what this is all about?

**Comment by craiggwilson** [comment]
Does it fix itself later?

**Comment by ghost** [comment]
Negative on that one. Still complaining about not being able to talk to MongoDB.

**Comment by craiggwilson** [comment]
Ok, I'll try and look into this today.  This adapter is sorely behind and needs to get updated.  I have some time to do it this week.

**Comment by ghost** [comment]
I think I've tracked it down to this sequence of events:
- Simple.Data (NuGet latest) is installed
- Simple.Data.Mongodb (NuGet latest) is then installed afterwards

If Simple.Data.Mongodb is installed and only installs the Simple.Data dll that it requires, it works fine. I guess there's something new in the latest Simple.Data deployment that breaks the provider?

**Comment by craiggwilson** [comment]
Yes, I found the issue the other day.  It is actually related to a different issue, but the gist is that the newer versions of Simple.Data core added a method that is not implemented by the MongoDB adapter yet.  I had to push a fix to the Simple.Data core project to get the MongoDB adapter working again.  When Mark releases the next version of Simple.Data (maybe 1.0), I'll push an update to the MongoDB adapter that works.

**Comment by ghost** [comment]
Any update on the update?

**Comment by craiggwilson** [comment]
Yes.  I think it's fixed and has been pulled to master.  However, I don't think a new release has been published, so I'm waiting until that happens.

**Comment by Timothep** [comment]
Hi Craigg, Mark published the 1.0.0 release candidate a couple days ago. Do you want to wait further for the official release?

**Comment by craiggwilson** [comment]
Nope, I'll try and take a look this weekend or early next week.

**Comment by craiggwilson** [comment]
Posted a new version to nuget.  Post back if it doesn't work.
