### ISSUE TITLE
"No ADO Provider found" while running the unit test

### ISSUE THREAD

**Issue by Timothep** [craiggwilson/Simple.Data.MongoDB#13]
Hi there,

I was wondering if I need a particular setup to run the driver's unit tests. I tried running it against MongoDB 2.0.3 and 2.2.0 but I get the same error upon opening the Database: "No ADO Provider found".

Any idea what I'm missing?

**Comment by craiggwilson** [comment]
Not sure.  I'm going to work on it today and let you know.  There are some other bugs right now, but I believe the lastest release of Simple.Data core fixes them.

**Comment by craiggwilson** [comment]
I've pushed a new version to nuget.  Let me know if it doesn't fix your problem.  Also, checkout a class in my tests called DatabaseOpener if you need to brute force it.

**Comment by Timothep** [comment]
Thanks for the update, the tests are running perfectly fine now :D
