### ISSUE TITLE
Mongo c# driver v 1.7

### ISSUE THREAD

**Issue by pbagh** [craiggwilson/Simple.Data.MongoDB#14]
Hi there,

Any plans to add support for v 1.7 of the Mongo c# driver?

Thanks,

Patrick

**Comment by craiggwilson** [comment]
Yes, just need to get around to doing it.  We will be release v1.8 of the Mongo C#  driver within a month, so I'll likely just wait until then unless you really need it now.  Let me know.

**Comment by pbagh** [comment]
Not an urgent need.  I can wait for v1.8 of the c# driver.
