### ISSUE TITLE
Big change to SimpleQuery in Core

### ISSUE THREAD

**Issue by ThatRendle** [craiggwilson/Simple.Data.MongoDB#2]
Hi Craig,

As the only author of a full adapter, you're the only person I need to inform of a big change I just made to the internal implementation of SimpleQuery. The change makes it easier to work with in some ways, but it's very different from my first attempt.

Now, instead of having properties for stuff like Columns, Criteria and so on, there is a single property, Clauses, which is an enumerable of the abstract SimpleQueryClauseBase. The items in this list are derived classes representing query operations, so there is a SelectClause (equivalent to Columns), a WhereClause, and so on.

There is also a new out parameter on the RunQuery method, which allows you to return a list of the clauses your adapter didn't handle.

I hope this makes sense, and makes your life a little easier. Let me know if there's a problem.

Cheers,
Mark

**Comment by craiggwilson** [comment]
Thanks for the information. Shouldn't be a problem. I'll watch for when you  
release the next version and then I'll update the adapter.

On Jul 20, 2011 6:44am, markrendle  
reply@reply.github.com  
wrote:
