### ISSUE TITLE
FindBy_id doesn't work

### ISSUE THREAD

**Issue by eibrahim** [craiggwilson/Simple.Data.MongoDB#9]
How do I retrieve by _id...  I tried to do something like 

db.Users.FindBy_id("4f7bb0006355aa1354a4c814") and it can't find anything.

I appologize if this is not the right place to post a question but I couldn't find anywhere else to post.  Thanks.

**Comment by craiggwilson** [comment]
You can just use FindById.  With that being said, unless your ids are getting stored as a string, you'll need to pass an ObjectId in.

**Comment by eibrahim** [comment]
I changed the id to a string, so I did something like this:

user.Id = ObjectId.GenerateNewId().ToString()
db.Users.Insert(user)

Then I can simply FindByUserId

It didn't work when Id was of type ObjectId...  But that's probably because I was calling FindById with a string not an ObjectId object...  I hope that makes sense and helps others...

Thanks.
